GPA.Kafka.PuSub/Models/ConfigurationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GPA.Kafka.PuSub.Models
{
    public class ConfigurationModel
    {
        public string BootstrapServers { get; set; }
        public string Topic { get; set; }
        public string ClientId { get; set; }
        public bool EnableAutoCommit { get; set; }
        public bool EnableAutoOffsetStore { get; set; }
        public int AutoOffsetReset { get; set; }
    }
}

GPA.Kafka.PuSub/Models/ConsumerConfigModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GPA.Kafka.PuSub.Models
{
    public class ConsumerConfigModel
    {
        public string BootstrapServers { get; set; }
        public string Topic { get; set; }
        public string GroupId { get; set; }
        public bool EnableAutoCommit { get; set; }
        public bool EnableAutoOffsetStore { get; set; }
        public int AutoOffsetReset { get; set; } 
        public int Loop { get; set; } = 1;
    }
}

GPA.Kafka.PuSub/Models/PublishConfigModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GPA.Kafka.PuSub.Models
{
    public class PublishConfigModel
    {
        public string BootstrapServers { get; set; }
        public string ClientId { get; set; }
        public string Payload { get; set; }
        public string Topic { get; set; }
    }
}

GPA.Kafka.PuSub/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GPA.Kafka.PuSub.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GPA.Kafka.PuSub/Pages/Index.cshtml.cs
using Confluent.Kafka;
using GPA.Kafka.PuSub.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace GPA.Kafka.PuSub.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;

        }

        [BindProperty]
        public PublishConfigModel PublishConfig { get; set; }
        [BindProperty]
        public ConsumerConfigModel ConsumeConfig { get; set; }

        public void OnGet()
        {

        }

        public void OnPost()
        {

        }

        public void OnPostPublishAsync(CancellationToken stoppingToken)
        {
            ViewData["Publish Result"] = "";
            ViewData["Fail Result"] = "";
            ViewData["Success Result"] = "";
            if (String.IsNullOrEmpty(PublishConfig.BootstrapServers)) { ViewData["Publish Result"] = "Error: BootstrapServes invalid parameter"; return; }
            if (String.IsNullOrEmpty(PublishConfig.ClientId)) { ViewData["Publish Result"] = "Error: GroupId invalid parameter"; return; }

            var config = new ProducerConfig
            {
                BootstrapServers = PublishConfig.BootstrapServers,
                ClientId = PublishConfig.ClientId                
            };

            var result = true;
            using (var producer = new ProducerBuilder<Null, string>(config).Build())
            {
                var t = producer.ProduceAsync(PublishConfig.Topic, new Message<Null, string> { Value = PublishConfig.Payload }, stoppingToken);
                t.ContinueWith(task =>
                {
                    if (task.Exception == null) { result = true; }
                    else { result = false; }
                });
                if (result)
                {
                    ViewData["Publish Result"] = "";
                    ViewData["Fail Result"] = "";
                    ViewData["Success Result"] = "Success";
                    //msg enviada
                }
                else
                {
                    ViewData["Publish Result"] = "";
                    ViewData["Success Result"] = "";
                    ViewData["Fail Result"] = "Fail";
                }
                producer.Flush(TimeSpan.FromSeconds(5));
                producer.Dispose();

            }
        }

        public void OnPostConsumeAsync(CancellationToken stoppingToken)
        {
            ViewData["Consume Result"] = "";
            if (String.IsNullOrEmpty(ConsumeConfig.BootstrapServers)) { ViewData["Consume Result"] = "Error: BootstrapServes invalid parameter"; return; }
            if (String.IsNullOrEmpty(ConsumeConfig.GroupId)) { ViewData["Consume Result"] = "Error: GroupId invalid parameter"; return; }
            if (String.IsNullOrEmpty(ConsumeConfig.Topic)) { ViewData["Consume Result"] = "Error: Topic invalid parameter"; return; }
            ConsumeConfig.AutoOffsetReset = int.Parse( Request.Form["OffsetType"]);            

            var config = new ConsumerConfig
            {
                BootstrapServers = ConsumeConfig.BootstrapServers,
                GroupId = ConsumeConfig.GroupId,
                EnableAutoCommit = ConsumeConfig.EnableAutoCommit,
                EnableAutoOffsetStore = ConsumeConfig.EnableAutoOffsetStore,
                AutoOffsetReset = (AutoOffsetReset)ConsumeConfig.AutoOffsetReset,
                
            };

            using (var consumer = new ConsumerBuilder<Ignore, string>(config).Build())
            {
                try
                {
                    var viewResult = "";
                    consumer.Subscribe(ConsumeConfig.Topic);
                    for (int i = 0; i < ConsumeConfig.Loop; i++)
                    {
                        var consumeResult = consumer.Consume(stoppingToken).Message;
                        viewResult += (string)consumeResult.Value + Environment.NewLine + Environment.NewLine;
                        ViewData["Messages"] = viewResult;
                    }
                    consumer.Close();
                }
                catch (Exception ex)
                {

                    ViewData["Consume Result"] = ex.ToString();
                }
                

            }
        }
    }
}

GPA.Kafka.PuSub/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GPA.Kafka.PuSub.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GPA.Kafka.PuSub/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";

}

<div class="row" style="font-size:11px;">

    <div style="width: 46%;  margin-bottom:20px; ">

        <form method="post">
            <table style="width: 100%; ">
                <tr>
                    <td><lable>Servers:</lable></td>
                    <td><input type="text" asp-for="PublishConfig.BootstrapServers" placeholder="Server1:port,Server2:port" /></td>
                </tr>
                <tr>
                    <td><lable>Group_Id:</lable></td>
                    <td><input type="text" asp-for="PublishConfig.ClientId" placeholder="Client Id" /></td>
                </tr>
                <tr>
                    <td><lable>Topic:</lable></td>
                    <td><input type="text" asp-for="PublishConfig.Topic" placeholder="Topic" /></td>
                </tr>
            </table>
            <div style="margin-top:20px;">
                <h6>Publish</h6>

                <label>Payload:</label>
                <textarea type="text" asp-for="PublishConfig.Payload" style="width:100%; min-height:296px;" placeholder="{ }"></textarea>
                <button type="submit" style="margin:20px 0px 0px 0px;" asp-page-handler="Publish">Publish</button>
                <b style="margin-left:20px; color:yellowgreen">@ViewData["Success Result"]</b>
                <b style="margin-left:20px;color:red">@ViewData["Fail Result"]@ViewData["Publish Result"]</b>

            </div>
        </form>
    </div>

    <div style="width: 4%;">
    </div>
    <div style="width: 4%; border-left:solid 1px; border-left-color:darkgray;">
    </div>

    <div style="width: 46%; margin-bottom: 20px;">

        <form method="post">
            <table style="width: 100%; " id="FormTable2">
                <tr>
                    <td><lable>Servers:</lable></td>
                    <td><input type="text" asp-for="ConsumeConfig.BootstrapServers" placeholder="Server1:port,Server2:port" /></td>
                </tr>
                <tr>
                    <td><lable>Group_Id: </lable></td>
                    <td><input type="text" asp-for="ConsumeConfig.GroupId" placeholder="Group Id" /></td>
                </tr>
                <tr>
                    <td><lable>Topic: </lable></td>
                    <td><input type="text" asp-for="ConsumeConfig.Topic" placeholder="Topic" /></td>
                </tr>
                <tr>
                    <td><lable>AutoCommit</lable></td>
                    <td><input type="checkbox" asp-for="ConsumeConfig.EnableAutoCommit" /></td>
                </tr>
                <tr>
                    <td><lable>AutoOffsetStore</lable></td>
                    <td><input type="checkbox" asp-for="ConsumeConfig.EnableAutoOffsetStore" /></td>
                </tr>
                <tr>
                    <td><lable style="margin:10px 0px 0px 0px;">AutoOffsetReset</lable></td>
                    <td>
                        <select id="OffsetType" asp-for="ConsumeConfig.AutoOffsetReset" name="OffsetType">

                            <option selected="selected" value="0">Latest</option>

                            <option value="1">Earliest</option>

                            <option value="2">None</option>

                        </select>
                    </td>
                </tr>
            </table>        
            <div style="margin-top:20px;">
                <h6>Consume</h6>

                <label>Message:</label>
                <textarea type="text" style="width:100%; min-height:247px;">@ViewData["Messages"]</textarea>
                <button type="submit" style="margin:20px 0px 0px 0px;" asp-page-handler="Consume">Consume</button>
                <input type="number" asp-for="ConsumeConfig.Loop" placeholder="1" style="width:60px;" />
                <b style="margin-left:20px;color:red">@ViewData["Consume Result"]</b>

            </div>
        </form>

        

    </div>
</div>

GPA.Kafka.PuSub/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GPA.Kafka.PubSub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <table style="width: 100%; ">
                    <tr>
                        <td><img src="~/lib/2560px-GPA_logo_2013.svg.png" height="40" style="margin-right:30px;"></img></td>
                        <td>GPA.Kafka.PubSub </td>
                    </tr>
                </table>
                @*<a class="navbar-brand" asp-area="" asp-page="/Index">GPA.Kafka.PubSub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GPA.Kafka.PuSub - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>